export const topUsers = [
  {
    userName: "BellsKing",
    image: "/assets/demo-images/p4.jpeg",
    bio: "Silicon Valley Bank collapse that led to USDC depeg: Every that's happended until now... #SVB #USDC",
    likes: 3509,
    comments: 384,
    multiplier: "x2",
    createdAt: "1h",
  },
  {
    userName: "CryptoLad",
    image: "/assets/demo-images/p8.jpeg",
    bio: "Silicon Valley Bank collapse that led to USDC depeg: Every that's happended until now... #SVB #USDC Silicon Valley Bank collapse that led to USDC depeg: Every that's happended until now... #SVB #USDC Silicon Valley Bank collapse that led to USDC depeg: Every that's happended until now... #SVB #USDC",
    likes: 2957,
    comments: 204,
    multiplier: "x1.75",
    createdAt: "2h",
  },
  {
    userName: "Mariett073",
    image: "/assets/demo-images/p1.jpeg",
    bio: "Silicon Valley Bank collapse that led to USDC depeg: Every that's happended until now... #SVB #USDC",
    likes: 1046,
    comments: 145,
    multiplier: "x1.5",
    createdAt: "34min",
  },
];

export const relevantThreadsAux =
  [{
    userName: "Hash0xfff",
    image: "/assets/demo-images/p13.jpeg",
    title: "ERC-4337 crypto wallets will onboard the next 1 billion users to web3. Here's how it will help a normal user: (in simple words)...",
    createdAt: "1h",
    topic: "forYou",
    threads: [{
      text: "What is ERC-4337 Account abstraction? This is a new type of crypto wallet that gives you \"the same fratures a bank would without having to trust a bank\" it was in the proposal for years, it got approved and live yesterday. An announcment was made at the ETH Denver event.",
      likes: 10,
      comments: 2,
      createdAt: "1h",
    },
    {
      text: "Are you on of the guys who lost wallet access and forgot the key with a cryptopunk in it? Now there's a solution. You can recovery you wallet with \"Social recovery\" if you lose your keys. No more lost assets.",
      likes: 7,
      comments: 3,
      createdAt: "2h",
    }],
    likes: 25,
    comments: 5,
    multiplier: "x2",
  },
  {
    userName: "Barb54",
    image: "/assets/demo-images/p6.jpeg",
    title: "New Crypto Wallets: Easier Access to Web3 (Think Bank-Level Features, Without the Bank)",
    createdAt: "2h",
    topic: "market",
    threads: [{
      text: "Forget complex keys! ERC-4337 lets you manage crypto like online banking, with added security features. It's finally here!",
      likes: 10,
      comments: 2,
      createdAt: "2h",
    },
    {
      text: "Lost your key and worried about your crypto? No sweat! Social recovery lets you regain access even if you forget your key.",
      likes: 7,
      comments: 3,
      createdAt: "3h",
    }],
    likes: 25,
    comments: 5,
    multiplier: "x2",
  },
  {
    userName: "CryptoCurious",
    image: "/assets/demo-images/p2.jpeg",
    title: "Beyond Bitcoin: Exploring the Potential of Decentralized Apps (dApps)",
    createdAt: "1d",
    topic: "blockchain",
    threads: [{
      text: "Imagine apps you control, not corporations! dApps run on blockchains, offering secure and transparent alternatives to traditional apps. What are you most excited about for dApps?",
      likes: 15,
      comments: 4,
      createdAt: "1d",
    },
    {
      text: "Security and transparency are key benefits of blockchain. Every transaction is recorded publicly, making fraud nearly impossible.  #blockchainsecurity",
      likes: 8,
      comments: 1,
      createdAt: "1d",
    }],
    likes: 32,
    comments: 7,
    multiplier: "x3",
  },
  {
    userName: "Block_Explorer",
    image: "/assets/demo-images/p7.jpeg",
    title: "Blockchain for Social Good: Solving Global Challenges Together",
    createdAt: "5h",
    topic: "nfts",
    threads: [
      {
        text: "Blockchain can be a powerful tool for social good. Imagine a transparent and secure system for tracking donations or voting rights. How can blockchain make a positive impact?",
        likes: 12,
        comments: 1,
        createdAt: "5h",
      },
      {
        text: "From fighting poverty to improving education, the possibilities are endless! Let's explore how blockchain can create a better future for all.",
        likes: 5,
        comments: 4,
        createdAt: "6h",
      },
    ],
    likes: 18,
    comments: 5,
    multiplier: "x1",
  },
  {
    userName: "Blockchain_Buzz",
    image: "/assets/demo-images/p9.jpeg",
    title: "Proof of Work vs. Proof of Stake: Understanding Blockchain Consensus Mechanisms",
    createdAt: "30m",
    topic: "defi",
    threads: [
      {
        text: "Not sure how transactions are validated on a blockchain? Proof of Work and Proof of Stake are two common consensus mechanisms. Learn how they work and their pros and cons!",
        likes: 5,
        comments: 2,
        createdAt: "30m",
      },
      {
        text: "Thinking of building your own blockchain? Understanding consensus mechanisms is crucial. Let's discuss the different options!",
        likes: 3,
        comments: 1,
        createdAt: "45m",
      },
    ],
    likes: 12,
    comments: 3,
    multiplier: "x1",
  },
  {
    userName: "CryptoBull",
    image: "/assets/demo-images/p3.jpeg",
    title: "The Future of Supply Chains: Blockchain Tracking for Transparency and Efficiency",
    createdAt: "2h",
    topic: "forYou",
    threads: [
      {
        text: "Imagine knowing exactly where your food comes from or the origin of your clothes! Blockchain can track products throughout the supply chain, ensuring authenticity and reducing fraud.",
        likes: 10,
        comments: 2,
        createdAt: "2h",
      },
      {
        text: "Blockchain supply chains benefit businesses too! Streamlined processes and reduced costs are just a few advantages.  #blockchainbusiness",
        likes: 7,
        comments: 3,
        createdAt: "3h",
      },
    ],
    likes: 25,
    comments: 5,
    multiplier: "x2",
  },
  {
    userName: "Blockchain_Analyst",
    image: "/assets/demo-images/p10.jpeg",
    title: "The Future of Finance: Decentralized Finance (DeFi) Explained",
    createdAt: "7h",
    topic: "market",
    threads: [
      {
        text: "Traditional finance is slow and complex. DeFi offers an alternative with peer-to-peer financial services built on blockchains.  Learn how DeFi is changing the game!",
        likes: 14,
        comments: 5,
        createdAt: "7h",
      },
      {
        text: "DeFi allows for borrowing, lending, and trading without banks!  But it also comes with risks.  Are you ready for the DeFi revolution?",
        likes: 9,
        comments: 2,
        createdAt: "8h",
      },
    ],
    likes: 21,
    comments: 7,
    multiplier: "x2",
  },
  {
    userName: "Cyber_Sec",
    image: "/assets/demo-images/p12.jpeg",
    title: "Blockchain Security: Myths and Realities",
    createdAt: "1d",
    topic: "blockchain",
    threads: [
      {
        text: "Is blockchain truly secure? Blockchains offer strong cryptography but are not invincible. Understanding the potential vulnerabilities is key!",
        likes: 12,
        comments: 8,
        createdAt: "1d",
      },
      {
        text: "Security is a shared responsibility on blockchains.  Learn best practices to keep your crypto safe.  #blockchainsecurity",
        likes: 7,
        comments: 4,
        createdAt: "1d",
      },
    ],
    likes: 28,
    comments: 12,
    multiplier: "x1",
  },
  {
    userName: "Green_Crypto",
    image: "/assets/demo-images/p11.jpeg",
    title: "Sustainable Blockchains: Reducing the Environmental Impact",
    createdAt: "2d",
    topic: "nfts",
    threads: [
      {
        text: "Blockchains can be energy-intensive. But there are solutions!  Explore sustainable blockchain projects that are reducing their environmental footprint.",
        likes: 8,
        comments: 3,
        createdAt: "2d",
      },
      {
        text: "Can blockchain technology be a force for good for the environment?  Let's discuss the possibilities for a greener future!",
        likes: 5,
        comments: 7,
        createdAt: "2d",
      },
    ],
    likes: 19,
    comments: 10,
    multiplier: "x3",
  },
  {
    userName: "Metaverse_Explorer",
    image: "/assets/demo-images/p5.jpeg",
    title: "The Metaverse: A Virtual World Powered by Blockchain",
    createdAt: "12h",
    topic: "defi",
    threads: [
      {
        text: "Imagine living, working, and playing in a virtual world! The Metaverse is coming, and blockchain is a key player.  What excites you most about the Metaverse?",
        likes: 18,
        comments: 11,
        createdAt: "12h",
      },
      {
        text: "The Metaverse has the potential to revolutionize how we interact, socialize, and even own digital assets.  Will it be the future of the internet?",
        likes: 12,
        comments: 6,
        createdAt: "13h",
      },
    ],
    likes: 35,
    comments: 17,
    multiplier: "x4",
  },
  { // New element 2
    userName: "Privacy_Advocate",
    image: "/assets/demo-images/p14.jpg",
    title: "Blockchain and Privacy: Balancing Transparency and Control",
    createdAt: "1d",
    topic: "defi",
    threads: [
      {
        text: "Blockchains are transparent, but what about user privacy?  Explore privacy-focused blockchain projects that give you control over your data.",
        likes: 10,
        comments: 4,
        createdAt: "1d",
      },
      {
        text: "Is complete anonymity on blockchains possible? Let's discuss the trade-offs between transparency and privacy in blockchain technology.",
        likes: 7,
        comments: 9,
        createdAt: "1d",
      },
    ],
    likes: 24,
    comments: 13,
    multiplier: "x2",
  },
  { // New element 3
    userName: "Code_Crafter",
    image: "/assets/demo-images/p15.jpg",
    title: "Building on Blockchain: Programming for the Future",
    createdAt: "2d",
    topic: "forYou",
    threads: [
      {
        text: "Blockchain technology is rapidly evolving.  Learn the skills to build decentralized applications (dApps) and be a part of the future!",
        likes: 9,
        comments: 2,
        createdAt: "2d",
      },
      {
        text: "What are you most interested in building on the blockchain?  Share your ideas and let's explore the possibilities together!",
        likes: 5,
        comments: 8,
        createdAt: "2d",
      },
    ],
    likes: 16,
    comments: 10,
    multiplier: "x1",
  },
  ]